### ISSUE TITLE
Drastic

### ISSUE THREAD

**Issue by Kmog2185** [magneticchen/Daijishou#362]
Previously, games could be booted directly through the Drastic emulator on previous versions of this frontend. However, it now only loads to the menu, leaving no option to use DS games through external storage. Can this be fixed please?

**Comment by Jetup13** [comment]
It should have been already fixed do you have your platforms to update upon startup?

> Daijishou > Settings > Library > Update platforms automatically

You can update the platform manually:

> Highlight DS platform > 🖊️ > select the `nds - Drastic` bubble > edit `file.path` to `file.uri` > Save

**Comment by Kmog2185** [comment]
Those settings were already made, but it still doesn't boot.

**Comment by Kmog2185** [comment]
It was already file.uri, but worked when changed to file.path. Thanks for the help!
