### ISSUE TITLE
Amiga .hdf

### ISSUE THREAD

**Issue by sunjerk** [magneticchen/Daijishou#832]
How is that it can't see some HDF images of Amiga hard drives that Retroarch can see and play instead?

**Comment by Jetup13** [comment]
Sorry for the late reply. Daijishou checks and adds items to a platform based on hash. It checks the first 4MB's the last I remember. So its possible the hash is the same as another item or has the same first 4MB's as another (assuming the hdf is larger than 4MB's). Also double-check your list as sometimes the scraper can incorrectly scrape data of another game

**Comment by sunjerk** [comment]
No delay to apologize for, I checked and indeed this is it, lazymd5 generates the same hash for their first 4 megabytes, how can I overcome this?

**Comment by Jetup13** [comment]
From what I've seen this issue popping up for arcade games, it was solved by repacking the game. Since we can't exactly repack hdf (I'm not sure) you can try compressing .hdf to .zip. Puae should support .zip files

**Comment by sunjerk** [comment]
I compressed each one separately, as you suggested, and it worked! Thanks for your patience! I had already tried repacking them with xdftool, but it didn't solve the problem!

**Comment by Jetup13** [comment]
Glad it worked out for you!
